openapi: 3.0.0
info:
  title: Webhook API
  description: API para manejar notificaciones de Webhooks
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /webhook:
    post:
      summary: Endpoint para recibir Webhooks
      description: Este endpoint recibe datos enviados por un Webhook.
      operationId: handleWebhook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nombre que se enviará al webhook.
                  example: "Juan"
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de respuesta.
                    example: "Hola, Juan!"
        '400':
          description: Solicitud inválida
